apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-boot-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-app
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          imagePullPolicy: IfNotPresent
          image: ngomansible/my_private_repo:56 # Image that will be used to containers in the cluster
          ports:
          - containerPort: 8085 # The port that the container is running on in the cluster
